class NarrativeViewer{constructor(c){this.gameName=c.gameName||'Unknown';this.dataPath=c.dataPath||'data/passages.json';this.metaPath=c.metaPath||'data/meta.json';this.passages=[];this.meta={};this.currentView='narrative';this.searchQuery='';this.searchTimeout=null;this.batchSize=20;this.rendered=0}
async init(){try{const[pr,mr]=await Promise.all([fetch(this.dataPath),fetch(this.metaPath).catch(()=>null)]);const d=await pr.json();this.passages=d.passages||d;if(mr)this.meta=await mr.json();this.render();this.bindEvents();console.log(`Loaded ${this.passages.length} passages for ${this.gameName}`)}catch(e){document.querySelector('.content').innerHTML=`<div style="text-align:center;padding:4rem;color:#999"><h2>\u5c1a\u672a\u89e3\u6790</h2><p>\u6b64\u904a\u6232\u7684\u6558\u4e8b\u8cc7\u6599\u5c1a\u672a\u63d0\u53d6\u5b8c\u6210</p><p style="margin-top:1rem"><a href="../../" style="color:var(--accent)">\u2190 \u8fd4\u56de\u9996\u9801</a></p></div>`}}
render(){const c=document.querySelector('.content');if(!c)return;c.innerHTML='';this.rendered=0;const f=this.getFilteredPassages();const g=this.groupPassages(f);for(const[n,p]of Object.entries(g)){const s=document.createElement('div');s.className='section';s.innerHTML=`<div class="section-header" onclick="viewer.toggleSection(this)"><span class="section-toggle">\u25b6</span><h2>${n}</h2><span class="section-count">(${p.length})</span></div><div class="section-body" style="display:none"></div>`;c.appendChild(s);s._passages=p}const st=document.getElementById('total-passages');if(st)st.textContent=this.passages.length}
getFilteredPassages(){if(!this.searchQuery)return this.passages;const q=this.searchQuery.toLowerCase();return this.passages.filter(p=>{const t=(p.text_zh||p.text_en||p.text||'').toLowerCase();const l=(p.label||p.name||'').toLowerCase();const ch=(p.characters||[]).join(' ').toLowerCase();return t.includes(q)||l.includes(q)||ch.includes(q)})}
groupPassages(passages){const g={};for(const p of passages){let k;switch(this.currentView){case'scene':k=p.es_name||p.scene||p.map_name||'Unknown Scene';break;case'character':const ch=p.characters||[];k=ch.length?ch[0]:'No Character';break;default:k=p.branch_type||p.chapter||p.section||'Main'}if(!g[k])g[k]=[];g[k].push(p)}return g}
toggleSection(h){const b=h.nextElementSibling;const t=h.querySelector('.section-toggle');const o=b.style.display!=='none';if(o){b.style.display='none';t.classList.remove('open')}else{b.style.display='block';t.classList.add('open');if(!b.dataset.rendered){this.renderPassages(b,h.closest('.section')._passages);b.dataset.rendered='true'}}}
renderPassages(c,p){for(const x of p.slice(0,this.batchSize)){c.appendChild(this.createPassageEl(x))}if(p.length>this.batchSize){const m=document.createElement('button');m.className='filter-btn';m.style.margin='.5rem 0';m.textContent=`\u8f09\u5165\u66f4\u591a (${p.length-this.batchSize})`;m.onclick=()=>{m.remove();for(const x of p.slice(this.batchSize))c.appendChild(this.createPassageEl(x))};c.appendChild(m)}}
createPassageEl(p){const e=document.createElement('div');e.className='passage';const l=p.label||p.name||p.pid||'';const t=p.text_zh||p.text_en||p.text||'';const ch=(p.characters||[]).map(c=>`<span class="char-tag">${c}</span>`).join('');let choices='';if(p.choices&&p.choices.length){choices='<div class="choices">'+p.choices.map(c=>{const cond=c.condition?` <span class="condition">[${c.condition}]</span>`:'';return`<div class="choice">${c.text}${cond}</div>`}).join('')+'</div>'}e.innerHTML=`<div class="passage-header"><span class="passage-label">${l}</span><span>${ch}</span></div><div class="passage-text">${this.formatText(t)}</div>${choices}`;return e}
formatText(t){return t.replace(/\n/g,'<br>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/"([^"]+)":/g,'<span class="speaker">"$1":</span>')}
bindEvents(){const s=document.querySelector('.search-box');if(s){s.addEventListener('input',e=>{clearTimeout(this.searchTimeout);this.searchTimeout=setTimeout(()=>{this.searchQuery=e.target.value;this.render()},300)})}document.querySelectorAll('.view-tab').forEach(tab=>{tab.addEventListener('click',()=>{document.querySelectorAll('.view-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');this.currentView=tab.dataset.view;this.render()})})}}
let viewer;